name: build-deploy
on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps: 
    - name: Clone repository 
      uses: actions/checkout@v4
    - name: Build image
      run: docker build . --tag=$GITHUB_JOB
    - name: Remove image
      run: docker image rm -f $GITHUB_JOB
  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Clone repository 
      uses: actions/checkout@v4
    - name: Copy env
      env:
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        STRIPE_WEBHOOK: ${{ secrets.STRIPE_WEBHOOK }}
        STRIPE_WEBHOOK_TEST: ${{ secrets.STRIPE_WEBHOOK_TEST }}
        STRIPE_TEST: ${{ secrets.STRIPE_TEST }}
        STRIPE: ${{ secrets.STRIPE }}
      run: cp .env.example .env && sed -i -e "s/SMTP_PASSWORD=/SMTP_PASSWORD=$SMTP_PASSWORD/g" .env && sed -i -e "s/STRIPE_WEBHOOK_TEST=/STRIPE_WEBHOOK_TEST=$STRIPE_WEBHOOK_TEST/g" .env && sed -i -e "s/STRIPE_TEST=/STRIPE_TEST=$STRIPE_TEST/g" .env
    - name: deploy
      run: docker compose -f ci.docker-compose.yml up --build --detach --force-recreate
